
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# No locking on Ctrl-S
stty -ixon

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

alias gti="git"
alias :e="nvim"
alias gd="git diff"
alias tmp='cd $(mktemp -d)'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

function t {
    if [ -n "$1" ] && [ -d "$1" ]; then
        # On Ubuntu, sets the window title
        printf "\e]2;${1%/}\a"
        cd "$1"
    fi
    tmux -2 new-session \; split-window -h \; attach
}

# Clear the screen in an nvim-friendly way where we can scroll back
function c {
    for i in $(seq 0 $LINES); do echo; done
    clear
}

# Open nvim, do different things depending on the dest
function n {
    if [ "$#" -eq 0 ]
    then
        nvim -c ':vnew' -c ':terminal' -c ':NvimTreeOpen'
    elif [ "$#" -eq 1 ]
    then
        local dest="$1"
        if [ -d "$dest" ]
        then
            cd "$dest" || exit
            nvim -c ':vnew' -c ':terminal' -c ':NvimTreeOpen'
        else
            cd "$(dirname "$dest")" || exit
            nvim "$(basename "$dest")"
        fi
    else
        echo "expected 0 or 1 arguments, got $#"
        exit 1
    fi
}

# GHC(i) with custom set of packages

ghc-shell() {
  nix-shell -p "haskellPackages.ghcWithPackages (ps: with ps; [ $* ])"
}

ghci-with() {
  nix-shell \
    -p "haskellPackages.ghcWithPackages (ps: with ps; [ $* ])" \
    --run ghci
}

##
## history: http://mywiki.wooledge.org/BashFAQ/088
##

# Big history
HISTFILESIZE=10000
HISTSIZE=10000

# history -a causes an immediate write of all new history lines
# (instead of upon shell exit)
PROMPT_COMMAND="history -a"

# histappend which causes all new history lines to be appended, and ensures
# that multiple logins do not overwrite each other's history
shopt -s histappend

##
## prompt
##

PS1='\[\033[01;34m\]\w\[\033[00m\]\$ '

##
## completion
##

# Copied over from the default Ubuntu config
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

for bcfile in ~/.nix-profile/etc/bash_completion.d/* ; do
  . $bcfile
done

# Set up direnv
eval "$(direnv hook bash)"
